[0m11:40:19.840941 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1100306e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1121ab980>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111e92b70>]}


============================== 11:40:19.849185 | ad32feb2-4ac9-4cc5-90f6-5cb154318cf2 ==============================
[0m11:40:19.849185 [info ] [MainThread]: Running with dbt=1.9.4
[0m11:40:19.850414 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/Users/danielkim_mac/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt init build_mau', 'send_anonymous_usage_stats': 'True'}
[0m11:40:19.866858 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'PosixPath'.. Dictionary: {'dir': PosixPath('/Users/danielkim_mac/.dbt')}
[0m11:40:19.867375 [info ] [MainThread]: Creating dbt configuration folder at 
[0m11:40:19.869030 [debug] [MainThread]: Starter project path: /opt/anaconda3/lib/python3.12/site-packages/dbt/include/starter_project
[0m11:40:19.875966 [info ] [MainThread]: 
Your new dbt project "build_mau" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m11:40:19.876470 [info ] [MainThread]: Setting up your profile.
[0m11:43:42.685375 [info ] [MainThread]: Profile build_mau written to /Users/danielkim_mac/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m11:43:42.704573 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 202.95474, "process_in_blocks": "0", "process_kernel_time": 1.237661, "process_mem_max_rss": "162197504", "process_out_blocks": "0", "process_user_time": 3.819692}
[0m11:43:42.705817 [debug] [MainThread]: Command `dbt init` succeeded at 11:43:42.705577 after 202.96 seconds
[0m11:43:42.706615 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x13da75d60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111d9c530>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x13dcda7e0>]}
[0m11:43:42.707580 [debug] [MainThread]: Flushing usage events
[0m11:43:43.093027 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:26:19.565754 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108fc7320>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a385fd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a385d30>]}


============================== 12:26:19.571707 | 690bc34b-a1ad-43d9-8a4b-66b123972a7d ==============================
[0m12:26:19.571707 [info ] [MainThread]: Running with dbt=1.9.4
[0m12:26:19.572818 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/Users/danielkim_mac/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:26:19.573671 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/danielkim_mac/Desktop/data226/dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:26:19.575953 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.089640774, "process_in_blocks": "0", "process_kernel_time": 0.339205, "process_mem_max_rss": "93560832", "process_out_blocks": "0", "process_user_time": 1.797287}
[0m12:26:19.576985 [debug] [MainThread]: Command `dbt run` failed at 12:26:19.576787 after 0.09 seconds
[0m12:26:19.577625 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109f63980>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a1f89e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a385e80>]}
[0m12:26:19.578338 [debug] [MainThread]: Flushing usage events
[0m12:26:19.930285 [debug] [MainThread]: An error was encountered while trying to flush usage events
